# Docker Compose配置文件
# =======================
# 这个文件让你能够用一个简单的命令就启动整个服务
# 就像是一个"一键启动"按钮

version: '3.8'

services:
  # 思维导图服务
  mind-map-server:
    # 构建设置
    build:
      context: .
      dockerfile: Dockerfile
    
    # 容器名称
    container_name: mind-map-mcp-server
    
    # 端口映射：将容器的8090端口映射到主机的8090端口
    ports:
      - "${HOST_PORT:-8090}:${HTTP_PORT:-8090}"
    
    # 环境变量配置
    environment:
      # HTTP服务器端口 | HTTP server port
      - HTTP_PORT=${HTTP_PORT:-8090}
      # 主机绑定地址 | Host binding address
      - HTTP_HOST=${HTTP_HOST:-0.0.0.0}
      # 调试模式 | Debug mode
      - DEBUG=${DEBUG:-false}
    
    # 卷挂载：将主机目录挂载到容器内
    volumes:
      # 挂载临时文件和输出目录 | Mount temp and output directories
      - "${HOST_TEMP_PATH:-./temp}:/app/temp"
      - "${HOST_OUTPUT_PATH:-./output}:/app/output"
      # 可选：挂载日志文件 | Optional: mount log files
      - "${HOST_LOG_PATH:-./logs}:/app/logs"
    
    # 重启策略：除非手动停止，否则总是重启
    restart: unless-stopped
    
    # 健康检查：确保服务正常运行
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT:-8090}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 网络配置
    networks:
      - mind-map-network

# 网络定义
networks:
  mind-map-network:
    driver: bridge
    
# 卷定义（可选）
volumes:
  # 持久化数据卷 | Persistent data volumes
  mind-map-temp:
    driver: local
  mind-map-output:
    driver: local
  mind-map-logs:
    driver: local

# 使用说明 | Usage Instructions
# =================================
#
# 快速启动 | Quick Start:
#   docker-compose up -d
#
# 查看日志 | View logs:
#   docker-compose logs
#
# 停止服务 | Stop service:
#   docker-compose down
#
# 重新构建 | Rebuild:
#   docker-compose up --build -d
#
# 自定义端口 | Custom port:
#   HOST_PORT=8080 docker-compose up -d
#
# 开启调试模式 | Enable debug mode:
#   DEBUG=true docker-compose up -d
#
# 环境变量说明 | Environment Variables:
# - HOST_PORT: 主机端口 (默认8090) | Host port (default 8090)
# - HTTP_PORT: 容器内HTTP端口 (默认8090) | Container HTTP port (default 8090)
# - HTTP_HOST: 绑定地址 (默认0.0.0.0) | Bind address (default 0.0.0.0)
# - DEBUG: 调试模式 (默认false) | Debug mode (default false)
# - HOST_TEMP_PATH: 临时文件目录 | Temp files directory
# - HOST_OUTPUT_PATH: 输出文件目录 | Output files directory
# - HOST_LOG_PATH: 日志文件目录 | Log files directory